### ISSUE TITLE
`NS:ID` identifier scheme should be full-text searchable

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/signature-commons-metadata-api#13]
According to this: https://www.postgresql.org/docs/current/textsearch-parsers.html

`:` would be ignored, as such there is a short-term and long-term fix

- [x] short term: Replace unrecognized symbols with spaces when querying
- [ ] long term: replace `NS:ID` by `NS://ID`

**Comment by u8sand** [comment]
The short term fix has been addressed in 2d15540

**Comment by jeevangelista** [comment]
oh I guess my issue is already here

**Comment by u8sand** [comment]
@jeevangelista I think this is fixed no? Please open if this is not the case..

**Comment by jeevangelista** [comment]
fixed it here: https://github.com/MaayanLab/signature-commons-ui/commit/b814a43e606a743c603200553e3f22b2f728abf1
