### ISSUE TITLE
Fulltext search with colons don't work

### ISSUE THREAD

**Issue by jeevangelista** [MaayanLab/signature-commons-metadata-api#20]
Searching for NS:Term using fullTextSearch results in a tsquery error

#13 https://github.com/MaayanLab/signature-commons-ui/issues/204

**Comment by u8sand** [comment]
This was fixed already, it's broken on the UI. I attempted to fix it but found the current code a bit convoluted. I mentioned it to you a while back..

**Comment by jeevangelista** [comment]
Yeah I'm fixing that in the UI
this causes an error: https://amp.pharm.mssm.edu/signature-commons-metadata-api/signatures?filter={"where":{"meta": {"fullTextSearch": {"eq": "UBERON:0000945"}}}}
but this works (replacing colons with "_" as suggested on the other issue: https://amp.pharm.mssm.edu/signature-commons-metadata-api/signatures?filter={"where":{"meta": {"fullTextSearch": {"eq": "UBERON_0000945"}}}}

My problem now is mixing it with meta.ns:
`
{
    "where": {
        "or": [
            {
                "meta.UBERON": {
                    "ilike": "%0000945%"
                }
            },
            {
                "meta": {
                    "fullTextSearch": {
                        "eq": "UBERON_0000945"
                    }
                }
            }
        ]
    }
}
`

This does not seem to work. Is there something wrong with 
`
 {
                "meta.UBERON": {
                    "ilike": "%0000945%"
                }
            }
`
